config/routes.rb
Etherapi::Application.routes.draw do
# Home route
  root :to => "home#index"

  devise_for :users, :controllers => {:registrations => "registrations", :confirmations => "confirmations", :invitations => "invitations", :sessions => "sessions", :passwords => "passwords"}

  #Resources
  resources :users, only: [:edit, :update] do
    collection do
      get :admin_reset_password
      put :update_password
      put :update_account
    end
  end

  resources :dashboards, only: [:index]

  resources :appointments do
    collection do
      get :pending
    end
    member do
      get :get_session_log
      get :accept
      get :session
      get :decline
    end
  end

  match 'code_tables/get_code_table/:code_table_name' => 'code_tables#get_code_table', :via => :get, :as => "get_code_table", :defaults => { :format => 'json' }

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
      post :mark_as_read
    end
  end

  resources :notes, only: [:show, :update, :create] do
    collection do
      get :get_patient_notes
      get :get_patient_notes_for_type
      get :get_session_notes
    end
  end

  match 'patient/save_avatar' => 'patient#save_avatar', :via => :post, :as => "patient_save_avatar"
  match 'patient/get_avatar' => 'patient#get_avatar', :via => :get, :as => "patient_get_avatar"
  match 'patient/remove_avatar' => 'patient#remove_avatar', :via => :put, :as => "patient_remove_avatar"
  match 'patient/get_patient_info' => 'patient#get_patient_info', :via => :get, :as => "patient_get_patient_info"
  
  resources :patient, only: [:show, :edit, :update] do
    member do
      get :accept_invitation_from
    end
    collection do
      get :payment
      get :info
    end
  end
  resources :patient_profile_steps

  match 'therapist/searchform' => 'therapist#searchform', :via => :get, :as => "therapist_searchform"
  match 'therapist/search' => 'therapist#search', :via => :get, :as => "therapist_search"
  match 'therapist/searchresult' => 'therapist#searchresult', :via => :get, :as => "therapist_searchresult"
  match 'therapist/getpatientlist' => 'therapist#get_patient_list', :via => :get, :as => "therapist_getpatients"
  match 'therapist/patient/:patient_id' => 'therapist#patient', :via => :get, :as => "therapist_patient"
  match 'therapist/save_avatar' => 'therapist#save_avatar', :via => :post, :as => "therapist_save_avatar"
  match 'therapist/get_avatar' => 'therapist#get_avatar', :via => :get, :as => "therapist_get_avatar"
  match 'therapist/remove_avatar' => 'therapist#remove_avatar', :via => :put, :as => "therapist_remove_avatar"
  match 'therapist/get_relate_info' => 'therapist#get_relate_info', :via => :get, :as => "therapist_get_relate_info"
  resources :therapist do
    get "/profile", :action => 'profile'
    resources :availability, only: [:index, :show, :update]
  end

  resources :therapist_consents , only: [:index, :show, :edit, :create, :new, :update] do
    member do
      get 'acknowledge/:patient_id', :action => 'acknowledge'
    end
  end

  resources :therapist_profile_steps

  resources :session_log, only:[:update]
  match 'session_log/join/:appointment_id' => 'session_log#join', :via => :get, :as => "session_join"
  match 'session_log/getVSeeExitURI' => 'session_log#getVSeeExitURI', :via => :get, :as => "session_getVSeeExitURI"
  resources :session, only:[:index]

  match 'eligible/coverage' => 'eligible#coverage', :via => :post, :as => "eligible_coverage"
  match 'eligible/retrieve/:patient_id' => 'eligible#retrieve', :via => :get, :as => "eligible_retrieve"

  # NEWEST code from bitbucket
  # noted for checking
  #match 'charges/listcards/:stripe_customer_id' =>  'charges#listcards', :via => :get, :as => "charges_listcards"

  match 'charges/getpublishablekey' =>  'charges#getpublishablekey', :via => :get, :as => "charges_getpublishablekey"
  match 'charges/createcustomer/:stripeToken' =>  'charges#createcustomer', :via => :put, :as => "charges_createcustomer"
  match 'charges/createprecharge' =>  'charges#createprecharge', :via => :post, :as => "charges_createprecharge"
  match 'charges/listcards' =>  'charges#listcards', :via => :get, :as => "charges_listcards"
  match 'charges/addcard' =>  'charges#addcard', :via => :put, :as => "charges_addcard"
  match 'charges/deletecard' =>  'charges#deletecard', :via => :put, :as => "charges_deletecard"
  match 'charges/defaultcard' =>  'charges#defaultcard', :via => :put, :as => "charges_defaultcard"
  match 'charges/createtoken' =>  'charges#createtoken', :via => :get, :as => "charges_createtoken" # will remove
  match 'charges/chargecustomer' => 'charges#chargecustomer', :via => :post, :as => "charges_chargecustomer" # will remove
  # match 'charges/retrieve_charge' => 'charges#retrieve_charge', :via => :get
  #resources :charges
  #get 'charges/create' => 'charges#create'

  resources :patient_payment_cards

  ## Custom Home page
  match 'home/custom_index' => 'home#custom_index', :via => :get
  #static pages
  get "site/faq"
  get "site/terms"
  get "site/about"
  get "site/support"
  get "site/press"
  get "site/security"
  get "site/contact"
  get "site/pricing"
  get "site/privacy"
  get "site/blog"
  get "site/map"
  get "site/therapist"

  # debug dashboard
  resources :debug do
    collection do
      get :therapist_without_any_appointment
      get :therapist_with_confirm_and_pending_appointment
      get :therapist_with_all_pending_appointment
      get :therapist_with_all_cancel_appointment
      get :therapist_with_all_cancel_request_upcomming_appointment
      get :therapist_with_canceled_appoitment_over_24h
      get :therapist_with_canceled_appoitment_in_24h
      get :normal_patient_with_request_upcomming_cancle_appointment
      get :therapist_with_patient_has_medical_histories
      get :login_with_therapist_without_any_appointment
      get :login_with_therapist_with_confirm_and_pending_appointment
      get :login_with_therapist_with_patient_has_medical_histories
      get :login_with_therapist_with_all_pending_appointment
      get :login_with_therapist_with_all_cancel_request_upcomming_appointment
      get :login_with_therapist_with_canceled_appoitment_in_24h
      get :login_with_therapist_with_canceled_appoitment_over_24h
      get :login_with_normal_patient_with_request_upcomming_cancle_appointment
    end
  end

  # match 'account_info' => 'accounts#show', :via => :get
  resources :profiles, only:[:show]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :imports do
    collection do
      post :language
      post :state
      post :country
      post :timezone
      post :insurance_company
      post :speciality
    end
  end

end

app/views/shared/_links.haml
- if controller_name != 'sessions'
  = link_to "Sign in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/shared/_navigation.html.haml
%h1 Menus
%table{:style=>"border: 1px; width: 100%", :border=>"1"}
  %tr
    %td
      Navigation    
    %td
      All users
    %td
      Therapist
    %td
      Patient
    %td
      Admininstrator
    %td
      Guests
    %td
      About
      
  %tr
    %td
      %li
        = link_to 'Home', root_path
      - if user_signed_in?
        %li
          = link_to('Logout', destroy_user_session_path, :method=>'delete')
      - else
        %li
          = link_to('Login', new_user_session_path)
        %li
          = link_to 'Sign up', new_user_registration_path(:account_type => 'Therapist')
    %td
      - if user_signed_in?
        %li
          = link_to('Dashboard', dashboards_path)
        %li
          = link_to('Edit account/Change Password', edit_user_registration_path)
    %td
      - if user_signed_in?
        - if current_user.is_therapist?
          %li
            = link_to('Therapist Profile Edit', edit_therapist_path(current_user))
          %li
            = link_to('Therapist Profile wizard', therapist_profile_steps_path)
          - if !current_user.getProfileable.therapist_id.blank?            
            %li
              = link_to("View Public Profile", therapist_profile_path(current_user.getProfileable.therapist_id))              
          %li
            = link_to('Invite Patient', new_user_invitation_path)
          %li
            = link_to('Availability settings', availability_index_path)
          %li
            = link_to('Request an Appointment', new_appointment_path)
          %li
            = link_to('View my Appointments', appointments_path)
          %li
            = link_to('View pending Appointments', pending_appointments_path)
          %li
            = link_to('View My Conversations', conversations_path)
          %li
            = link_to('Consents', therapist_consents_path)
            
      
    %td
      - if user_signed_in?
        - if current_user.is_patient?
          %li
            = link_to('Patient Profile Edit', edit_patient_path(current_user))      
          %li
            = link_to('Patient Profile wizard', patient_profile_steps_path)
          %li
            = link_to('View my Appointments', appointments_path)
          %li
            = link_to('View pending Appointments', pending_appointments_path)
          %li
            = link_to('View My Conversations', conversations_path)
          
      
    %td
      - if user_signed_in?
        - if current_user.is_admin?
          = link_to 'Active Admin', admin_dashboard_path
    %td
      %li
        = link_to('Search', therapist_searchform_path)
      %li
        = link_to('Forgot Password', new_user_password_path)
      %li
        = link_to('Password reset email', edit_user_password_path)
      %li
        = link_to('User Confirmation', new_user_confirmation_path)
    %td
      %li
        = link_to "About", site_about_path
      %li
        = link_to "FAQ", site_faq_path
      %li
        = link_to "Terms and Conditions", site_terms_path
      %li
        = link_to "Security", site_security_path
      %li
        = link_to "Support", site_support_path
      %li
        = link_to "Press", site_press_path
      %li 
        = link_to "Contact", site_contact_path
      %li
        = link_to "Blog", site_blog_path 
      %li
        = link_to "Privacy", site_privacy_path
      %li
        = link_to "Pricing", site_pricing_path
      %li
        = link_to "Site Map", site_map_path
                 

app/views/shared/_patient_profile_account.html.haml
.field
  = patient_form.label :first_name
  %br
  = patient_form.text_field :first_name
  
.field
  = patient_form.label :last_name
  %br
  = patient_form.text_field :last_name
  
.field
  = patient_form.label :middle_name
  %br
  = patient_form.text_field :middle_name

.field
  = patient_form.label :nick_name
  %br
  = patient_form.text_field :nick_name

.field
  = patient_form.label :date_of_birth
  %br
  = patient_form.date_select :date_of_birth, start_year: 1900, end_year: Date.today.year, include_blank: true

.field
  = patient_form.label :ssn
  %br
  = patient_form.text_field :ssn

.field
  = patient_form.label :language
  %br
  = patient_form.collection_select(:language, LanguageCde.all, :language_code, :language, :include_blank => "Select a Language" )

.field
  = patient_form.label :gender
  %br
  = patient_form.select :gender, options_for_select([["Select One", ""], ["Male", "M"], ["Female", "F"]], :selected => patient_form.object.gender)
  
.field
  = patient_form.label :timezone
  %br
  = patient_form.collection_select(:timezone, TimezoneCde.all, :id, :name, :include_blank => "Select a TimeZone" )
.field
  = patient_form.label :phone_work
  %br
  = patient_form.text_field :phone_work

.field
  = patient_form.label :phone_home
  %br
  = patient_form.text_field :phone_home

.field
  = patient_form.label :phone_mobile
  %br
  = patient_form.text_field :phone_mobile

.field
  = patient_form.label :medical_history
  %br
  = patient_form.text_field :medical_history

.field
  = patient_form.label :picture_filelink
  %br
  = patient_form.text_field :picture_filelink

app/views/shared/_patient_profile_address.html.haml
%table{:style=>"border: 1px; width: 100%", :border=>"1"}
  %tr
    %td{:style=>"width: 50%"}
      %h2 Address
    %td{:style=>"width: 50%"}
      %h2 Mailing address
  %tr
    %td
      .field
        = patient_form.label :address1
        %br/
        = patient_form.text_field :address1
        
      .field
        = patient_form.label :address2
        %br/
        = patient_form.text_field :address2
        
      .field
        = patient_form.label :city
        %br/
        = patient_form.text_field :city
    
      .field
        = patient_form.label :state_cde
        %br/
        = patient_form.collection_select(:state_cde, StateCde.all, :id, :name, :include_blank => "Select a State" )
      .field
        = patient_form.label :zipcode
        %br/
        = patient_form.text_field :zipcode
      .field
        = patient_form.label :country_cde
        %br/
        = patient_form.collection_select(:country_cde, CountryCde.all, :id, :name, :include_blank => "Select a Country" )
    %td
      .field
        = patient_form.label :mail_address1
        %br/
        = patient_form.text_field :mail_address1
        
      .field
        = patient_form.label :mail_address2
        %br/
        = patient_form.text_field :mail_address2
        
      .field
        = patient_form.label :mail_city
        %br/
        = patient_form.text_field :mail_city
    
      .field
        = patient_form.label :mail_state_cde
        %br/
        = patient_form.collection_select(:mail_state_cde, StateCde.all, :id, :name, :include_blank => "Select a State" )
      .field
        = patient_form.label :mail_zipcode
        %br/
        = patient_form.text_field :mail_zipcode
      .field
        = patient_form.label :mail_country_cde
        %br/
        = patient_form.collection_select(:mail_country_cde, CountryCde.all, :id, :name, :include_blank => "Select a Country" )

app/views/shared/_patient_profile_insurance.html.haml
.field
  = patient_form.fields_for :patient_insurance do |insurance_form|
    .field
      = insurance_form.label :policy_number
      = insurance_form.text_field :policy_number
    .field
      = insurance_form.label :group_number
      = insurance_form.text_field :group_number
    .field
      = insurance_form.label :group_name
      = insurance_form.text_field :group_name
    .field
      = insurance_form.label :seq
      = insurance_form.select :seq, options_for_select([["Select One", ""], ["Primary", "1"], ["Secondary", "2"], ["Tertiary", "3"], ["Other", "9"]])        
    .field
      = insurance_form.label :subscriber_last_name
      = insurance_form.text_field :subscriber_last_name
    .field
      = insurance_form.label :subscriber_first_name
      = insurance_form.text_field :subscriber_first_name
    .field
      = insurance_form.label :subscriber_dob
      = insurance_form.date_select :subscriber_dob, start_year: 1900, end_year: Date.today.year, include_blank: true
    .field
      = insurance_form.label :subscriber_address1
      = insurance_form.text_field :subscriber_address1
    .field
      = insurance_form.label :subscriber_address2
      = insurance_form.text_field :subscriber_address2
    .field
      = insurance_form.label :subscriber_city
      = insurance_form.text_field :subscriber_city
    .field
      = insurance_form.label :subscriber_state_cde
      = insurance_form.collection_select(:subscriber_state_cde, StateCde.all, :id, :name, :include_blank => "Select a State" )
    .field
      = insurance_form.label :subscriber_zipcode
      = insurance_form.text_field :subscriber_zipcode
    .field
      = insurance_form.label :subscriber_country_cde
      = insurance_form.collection_select(:subscriber_country_cde, CountryCde.all, :id, :name, :include_blank => "Select a Country" )
    .field
      = insurance_form.label :subscriber_relationship
      = insurance_form.text_field :subscriber_relationship
      

    = insurance_form.link_to_remove "Remove this insurance"
    %p
  = patient_form.link_to_add "Add an insurance", :patient_insurance

app/views/shared/_therapist_availability.html.haml
.field
  = therapist_form.fields_for :therapist_availability do |availability_form|
    .field
      = availability_form.label :date
      = availability_form.date_select :date, start_year: Date.today.year, start_month: Date.today.month, end_year: 2050, include_blank: true
    .field
      = availability_form.label :start_time
      = availability_form.time_select :start_time, include_blank: true
    .field
      = availability_form.label :end_time
      = availability_form.time_select :end_time, include_blank: true
    .field
      = availability_form.hidden_field :id
    = availability_form.link_to_remove "Remove this availability"
    %p
  %p
    = therapist_form.link_to_add "Add a availability", :therapist_availability

app/views/shared/_therapist_availability_list.html.haml
%h3 Single Availability
- @therapist.get_availabilities.each do |s|
  - s.each do |o|
    = o.start_time
    to
    = o.end_time
    %br

%h3 Rucuring Availability
- @therapist.get_recuring_availabilities(2014, 5).each do |s|
  %h3 Schedule
  %br
  - s.each do |o|
    = o.start_time
    to
    = o.end_time
    day
    = o.start_time.strftime("%d/%m/%Y %A %u")
    %br

app/views/shared/_therapist_availability_rec.html.haml
.field
  = therapist_form.fields_for :therapist_availability_rec do |recurring_availability_form|
    .field
      = recurring_availability_form.label :start_date
      = recurring_availability_form.date_select :start_date, start_year: Date.today.year, end_year: 2050, include_blank: true
    .field
      = recurring_availability_form.label :end_date
      = recurring_availability_form.date_select :end_date, start_year: Date.today.year, end_year: 2050, include_blank: true
      
    .field
      = recurring_availability_form.label :start_time
      = recurring_availability_form.time_select :start_time, start_year: Date.today.year, end_year: 2050, include_blank: true
    .field
      = recurring_availability_form.label :end_time
      = recurring_availability_form.time_select :end_time, start_year: Date.today.year, end_year: 2050, include_blank: true
    .field
      = recurring_availability_form.label :recurring_type
      = recurring_availability_form.select :recurring_type, options_for_select([["Select One", ""], ["Daily", "daily"], ["Weekly", "weekly"], ["Monthly", "monthly"]], :selected => recurring_availability_form.object.recurring_type)
    .field
      = recurring_availability_form.label :daily_every_no_days
      = recurring_availability_form.select :daily_every_no_days, options_for_select([["Select One", ""], ["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"], ["6", "6"], ["7", "7"]], :selected => recurring_availability_form.object.daily_every_no_days)
    .field
      = recurring_availability_form.label :daily_every_weekday
      = recurring_availability_form.check_box :daily_every_weekday
    .field
      = recurring_availability_form.label :weekly_sunday
      = recurring_availability_form.check_box :weekly_sunday
    .field
      = recurring_availability_form.label :weekly_monday
      = recurring_availability_form.check_box :weekly_monday
    .field
      = recurring_availability_form.label :weekly_tuesday
      = recurring_availability_form.check_box :weekly_tuesday
    .field
      = recurring_availability_form.label :weekly_wednesday
      = recurring_availability_form.check_box :weekly_wednesday
    .field
      = recurring_availability_form.label :weekly_thursday
      = recurring_availability_form.check_box :weekly_thursday
    .field
      = recurring_availability_form.label :weekly_friday
      = recurring_availability_form.check_box :weekly_friday
    .field
      = recurring_availability_form.label :weekly_saturday
      = recurring_availability_form.check_box :weekly_saturday    
    .field
      = recurring_availability_form.hidden_field :id
    = recurring_availability_form.link_to_remove "Remove this availability"
    %p
  %p
    = therapist_form.link_to_add "Add a recurring availability", :therapist_availability_rec

app/views/shared/_therapist_profile_account.html.haml
%h3 Avatar
=image_tag(therapist.picture_filelink.to_s, size: "200x300")
.field
  = therapist_form.label :avatar
  %br/
  = therapist_form.file_field :picture_filelink

.field
  = therapist_form.label :first_name
  %br/
  = therapist_form.text_field :first_name
  
.field
  = therapist_form.label :last_name
  %br/
  = therapist_form.text_field :last_name
  
.field
  = therapist_form.label :middle_name
  %br/
  = therapist_form.text_field :middle_name

.field
  = therapist_form.label :nick_name
  %br/
  = therapist_form.text_field :nick_name

.field
  = therapist_form.label :npi_no
  %br/
  = therapist_form.text_field :npi_no

.field
  = therapist_form.label :gender
  %br/
  = therapist_form.select :gender, options_for_select([["Select One", ""], ["Male", "M"], ["Female", "F"]], :selected => therapist_form.object.gender)
 
.field
  = therapist_form.label :timezone
  %br/
  = therapist_form.collection_select(:timezone, TimezoneCde.all, :id, :name, :include_blank => "Select a TimeZone" )
  
.field
  = therapist_form.label :phone_work
  %br/
  = therapist_form.text_field :phone_work

.field
  = therapist_form.label :phone_home
  %br/
  = therapist_form.text_field :phone_home

.field
  = therapist_form.label :phone_mobile
  %br/
  = therapist_form.text_field :phone_mobile
.field
  = therapist_form.label :session_duration
  %br/
  = therapist_form.select :session_duration, options_for_select([["Select One", ""], ["5", 5], ["10", 10], ["15", 15], ["20", 20], ["25", 25], ["30", 30], ["35", 35], ["40", 40], ["45", 45], ["50", 50], ["55", 55], ["60", 60]], :selected => therapist_form.object.session_duration)
  
.field
  = therapist_form.label :normal_wrk_start_time
  %br/
  = therapist_form.text_field :normal_wrk_start_time
.field
  = therapist_form.label :normal_wrk_end_time
  %br/
  = therapist_form.text_field :normal_wrk_end_time
    

app/views/shared/_therapist_profile_address.html.haml
%table{:style=>"border: 1px; width: 100%", :border=>"1"}
  %tr
    %td{:style=>"width: 50%"}
      %b Address
    %td{:style=>"width: 50%"}
      %b Mailing address
  %tr
    %td
      .field
        = therapist_form.label :address1
        %br/
        = therapist_form.text_field :address1
        
      .field
        = therapist_form.label :address2
        %br/
        = therapist_form.text_field :address2
        
      .field
        = therapist_form.label :city
        %br/
        = therapist_form.text_field :city
    
      .field
        = therapist_form.label :state_cde
        %br/
        = therapist_form.collection_select(:state_cde, StateCde.all, :id, :name, :include_blank => "Select a State" )
      .field
        = therapist_form.label :zipcode
        %br/
        = therapist_form.text_field :zipcode
      .field
        = therapist_form.label :country_cde
        %br/
        = therapist_form.collection_select(:country_cde, CountryCde.all, :id, :name, :include_blank => "Select a Country" )
    %td
      .field
        = therapist_form.label :mail_address1
        %br/
        = therapist_form.text_field :mail_address1
        
      .field
        = therapist_form.label :mail_address2
        %br/
        = therapist_form.text_field :mail_address2
        
      .field
        = therapist_form.label :mail_city
        %br/
        = therapist_form.text_field :mail_city
    
      .field
        = therapist_form.label :mail_state_cde
        %br/
        = therapist_form.collection_select(:mail_state_cde, StateCde.all, :id, :name, :include_blank => "Select a State" )
      .field
        = therapist_form.label :mail_zipcode
        %br/
        = therapist_form.text_field :mail_zipcode
      .field
        = therapist_form.label :mail_country_cde
        %br/
        = therapist_form.collection_select(:mail_country_cde, CountryCde.all, :id, :name, :include_blank => "Select a Country" )

app/views/shared/_therapist_profile_background.html.haml
.field
  = therapist_form.fields_for :therapist_profile do |profile_form|
    .field
      = profile_form.label :tag_line
      %br/
      = profile_form.text_field :tag_line
    .field
      = profile_form.label :about_me
      %br/
      = profile_form.text_field :about_me
    .field
      = profile_form.label :education
      %br/
      = profile_form.text_field :education
    .field
      = profile_form.label :school
      %br/
      = profile_form.text_field :school
    .field
      = profile_form.label :prof_memberships
      %br/
      = profile_form.text_field :prof_memberships
    .field
      = profile_form.label :experience_years
      %br/
      = profile_form.text_field :experience_years
    .field
      = profile_form.label :hourly_rate_min
      %br/
      = profile_form.text_field :hourly_rate_min
    .field
      = profile_form.label :hourly_rate_max
      %br/
      = profile_form.text_field :hourly_rate_max
    .field
      = profile_form.label :interview_dt
      %br/
      = profile_form.date_select :interview_dt, start_year: 2010, end_year: 2050, include_blank: true
    .field
      = profile_form.label :emergency_contact_person
      %br/
      = profile_form.text_field :emergency_contact_person
    .field
      = profile_form.label :emergency_contact_ph_number
      %br/
      = profile_form.text_field :emergency_contact_ph_number
    .field
      = profile_form.label :emergency_contact_rel
      %br/
      = profile_form.text_field :emergency_contact_rel
    .field
      = profile_form.label :sliding_scale
      %br/
      = profile_form.text_field :sliding_scale
    .field
      = profile_form.label :accept_new_patient
      %br/
      = profile_form.check_box  :accept_new_patient
    .field
      = profile_form.label :viewable_on_search
      %br/
      = profile_form.check_box  :viewable_on_search
    .field
      = profile_form.label :treatment_approach
      %br/
      = profile_form.text_field :treatment_approach
      Hint : Use comma delimited list
    .field
      = profile_form.label :client_focus
      Hint : Use comma delimited list
      %br/
      = profile_form.text_field :client_focus
    .field
      = profile_form.label :demographics_served
      Hint : Use comma delimited list
      %br/
      = profile_form.text_field :demographics_served
    .field
      = profile_form.label :youtube_link
      %br/
      = profile_form.text_field :youtube_link
    .field
      = profile_form.label :web_uri_link
      %br/
      = profile_form.text_field :web_uri_link
    .field
      = profile_form.label :hear_about_us_id
      %br/
      = profile_form.collection_select(:hear_about_us_id, HearAboutUsCde.all, :id, :hear_about_us, :include_blank => "Select an option" ) 

app/views/shared/_therapist_profile_insurance.html.haml
.field
  = therapist_form.fields_for :therapist_accept_insurance do |insurance_form|
    .field
      = insurance_form.label :insurance_id
      = insurance_form.collection_select(:insurance_id, InsuranceCompany.all, :insurance_id, :name, :include_blank => "Select a Company" )
    .field
      = insurance_form.label :contract_ref_no
      = insurance_form.text_field :contract_ref_no
    .field
      = insurance_form.label :start_date
      = insurance_form.date_select :start_date, start_year: 2000, end_year: 2050, include_blank: true
    .field
      = insurance_form.label :end_date
      = insurance_form.date_select :end_date, start_year: Date.today.year, end_year: 2050, include_blank: true
    .field
      = insurance_form.hidden_field :entity_id
    = insurance_form.link_to_remove "Remove this insurance"
    %p
  %p
    = therapist_form.link_to_add "Add an insurance", :therapist_accept_insurance

app/views/shared/_therapist_profile_language.html.haml
.field
= therapist_form.fields_for :therapist_language do |license_form|
  .field
    = license_form.label :language_cde
    = license_form.collection_select :language_cde, LanguageCde.all, :language_code, :language, :include_blank => "Select a Language"
  .field
    = license_form.label :proficiency
    = license_form.text_field :proficiency
  .field
    = license_form.hidden_field :id

  = license_form.link_to_remove "Remove this language"
%p
  = therapist_form.link_to_add "Add a language", :therapist_language
  %br

app/views/shared/_therapist_profile_speciality.html.haml
.field
  = therapist_form.fields_for :therapist_speciality do |speciality_form|
    .field
      = speciality_form.label :speciality_id
      = speciality_form.collection_select(:speciality_id, SpecialityCde.all, :speciality_id, :name, :include_blank => "Select a Speciality" )
      = speciality_form.select :seq_speciality_cde, options_for_select([["Select One", ""], ["Primary", 1], ["Other", 9]], :selected => speciality_form.object.seq_speciality_cde)
      = speciality_form.link_to_remove "Remove this speciality"
  %p
    = therapist_form.link_to_add "Add a Speciality", :therapist_speciality