config/routes.rb
Etherapi::Application.routes.draw do
# Home route
  root :to => "home#index"

  devise_for :users, :controllers => {:registrations => "registrations", :confirmations => "confirmations", :invitations => "invitations", :sessions => "sessions", :passwords => "passwords"}

  #Resources
  resources :users, only: [:edit, :update] do
    collection do
      get :admin_reset_password
      put :update_password
      put :update_account
    end
  end

  resources :dashboards, only: [:index]

  resources :appointments do
    collection do
      get :pending
    end
    member do
      get :get_session_log
      get :accept
      get :session
      get :decline
    end
  end

  match 'code_tables/get_code_table/:code_table_name' => 'code_tables#get_code_table', :via => :get, :as => "get_code_table", :defaults => { :format => 'json' }

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
      post :mark_as_read
    end
  end

  resources :notes, only: [:show, :update, :create] do
    collection do
      get :get_patient_notes
      get :get_patient_notes_for_type
      get :get_session_notes
    end
  end

  match 'patient/save_avatar' => 'patient#save_avatar', :via => :post, :as => "patient_save_avatar"
  match 'patient/get_avatar' => 'patient#get_avatar', :via => :get, :as => "patient_get_avatar"
  match 'patient/remove_avatar' => 'patient#remove_avatar', :via => :put, :as => "patient_remove_avatar"
  match 'patient/get_patient_info' => 'patient#get_patient_info', :via => :get, :as => "patient_get_patient_info"
  
  resources :patient, only: [:show, :edit, :update] do
    member do
      get :accept_invitation_from
    end
    collection do
      get :payment
      get :info
    end
  end
  resources :patient_profile_steps

  match 'therapist/searchform' => 'therapist#searchform', :via => :get, :as => "therapist_searchform"
  match 'therapist/search' => 'therapist#search', :via => :get, :as => "therapist_search"
  match 'therapist/searchresult' => 'therapist#searchresult', :via => :get, :as => "therapist_searchresult"
  match 'therapist/getpatientlist' => 'therapist#get_patient_list', :via => :get, :as => "therapist_getpatients"
  match 'therapist/patient/:patient_id' => 'therapist#patient', :via => :get, :as => "therapist_patient"
  match 'therapist/save_avatar' => 'therapist#save_avatar', :via => :post, :as => "therapist_save_avatar"
  match 'therapist/get_avatar' => 'therapist#get_avatar', :via => :get, :as => "therapist_get_avatar"
  match 'therapist/remove_avatar' => 'therapist#remove_avatar', :via => :put, :as => "therapist_remove_avatar"
  match 'therapist/get_relate_info' => 'therapist#get_relate_info', :via => :get, :as => "therapist_get_relate_info"
  resources :therapist do
    get "/profile", :action => 'profile'
    resources :availability, only: [:index, :show, :update]
  end

  resources :therapist_consents , only: [:index, :show, :edit, :create, :new, :update] do
    member do
      get 'acknowledge/:patient_id', :action => 'acknowledge'
    end
  end

  resources :therapist_profile_steps

  resources :session_log, only:[:update]
  match 'session_log/join/:appointment_id' => 'session_log#join', :via => :get, :as => "session_join"
  match 'session_log/getVSeeExitURI' => 'session_log#getVSeeExitURI', :via => :get, :as => "session_getVSeeExitURI"
  resources :session, only:[:index]

  match 'eligible/coverage' => 'eligible#coverage', :via => :post, :as => "eligible_coverage"
  match 'eligible/retrieve/:patient_id' => 'eligible#retrieve', :via => :get, :as => "eligible_retrieve"

  # NEWEST code from bitbucket
  # noted for checking
  #match 'charges/listcards/:stripe_customer_id' =>  'charges#listcards', :via => :get, :as => "charges_listcards"

  match 'charges/getpublishablekey' =>  'charges#getpublishablekey', :via => :get, :as => "charges_getpublishablekey"
  match 'charges/createcustomer/:stripeToken' =>  'charges#createcustomer', :via => :put, :as => "charges_createcustomer"
  match 'charges/createprecharge' =>  'charges#createprecharge', :via => :post, :as => "charges_createprecharge"
  match 'charges/listcards' =>  'charges#listcards', :via => :get, :as => "charges_listcards"
  match 'charges/addcard' =>  'charges#addcard', :via => :put, :as => "charges_addcard"
  match 'charges/deletecard' =>  'charges#deletecard', :via => :put, :as => "charges_deletecard"
  match 'charges/defaultcard' =>  'charges#defaultcard', :via => :put, :as => "charges_defaultcard"
  match 'charges/createtoken' =>  'charges#createtoken', :via => :get, :as => "charges_createtoken" # will remove
  match 'charges/chargecustomer' => 'charges#chargecustomer', :via => :post, :as => "charges_chargecustomer" # will remove
  # match 'charges/retrieve_charge' => 'charges#retrieve_charge', :via => :get
  #resources :charges
  #get 'charges/create' => 'charges#create'

  resources :patient_payment_cards

  ## Custom Home page
  match 'home/custom_index' => 'home#custom_index', :via => :get
  #static pages
  get "site/faq"
  get "site/terms"
  get "site/about"
  get "site/support"
  get "site/press"
  get "site/security"
  get "site/contact"
  get "site/pricing"
  get "site/privacy"
  get "site/blog"
  get "site/map"
  get "site/therapist"

  # debug dashboard
  resources :debug do
    collection do
      get :therapist_without_any_appointment
      get :therapist_with_confirm_and_pending_appointment
      get :therapist_with_all_pending_appointment
      get :therapist_with_all_cancel_appointment
      get :therapist_with_all_cancel_request_upcomming_appointment
      get :therapist_with_canceled_appoitment_over_24h
      get :therapist_with_canceled_appoitment_in_24h
      get :normal_patient_with_request_upcomming_cancle_appointment
      get :therapist_with_patient_has_medical_histories
      get :login_with_therapist_without_any_appointment
      get :login_with_therapist_with_confirm_and_pending_appointment
      get :login_with_therapist_with_patient_has_medical_histories
      get :login_with_therapist_with_all_pending_appointment
      get :login_with_therapist_with_all_cancel_request_upcomming_appointment
      get :login_with_therapist_with_canceled_appoitment_in_24h
      get :login_with_therapist_with_canceled_appoitment_over_24h
      get :login_with_normal_patient_with_request_upcomming_cancle_appointment
    end
  end

  # match 'account_info' => 'accounts#show', :via => :get
  resources :profiles, only:[:show]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :imports do
    collection do
      post :language
      post :state
      post :country
      post :timezone
      post :insurance_company
      post :speciality
    end
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :authenticate_user!
  authorize_resource :class => false
  def index
    @user = current_user
    @conversations = @user.mailbox.conversations
    if @user.is_admin?
      template = "dashboards/admin_dashboard"
    elsif @user.is_patient?
      @profile = Patient.where("user_id = ?", @user.user_id).first
      @my_invitations = TherapistPatient.get_my_invitations(@user.user_id)
      if !@profile.blank?
        @my_therapists = TherapistPatient.get_my_therapists(@user.user_id)
        @my_appointments = Appointment.where("patient_id = ?", @profile.id)
      end

      template = "dashboards/patient_dashboard"
    elsif @user.is_therapist?
      @profile = Therapist.where("user_id = ?", @user.user_id).first
      if !@profile.blank?
        @my_patients = TherapistPatient.get_my_patients(@user.user_id)
        @my_appointments = Appointment.where("therapist_id = ?", @profile.id)
      end

      template = "dashboards/therapist_dashboard"
    else
      raise 'Unknown user account type'
    end

    render :template => template
  end
end

app/views/dashboards/admin_dashboard.html.haml
%h1 Administrator Dashboard
%div{:class => "panel panel-default"}
  %h2 Reset User Password
  = form_tag admin_reset_password_users_path, :method => 'get' do
    = field_set_tag do
      = label_tag :user_id, 'User : '
      = select_tag :user_id, options_from_collection_for_select(User.all, "user_id", "email"), include_blank: true
      %br
      = label_tag :password, "New password"
      %br/
      = password_field_tag :password
      = label_tag :password_confirmation, "Confirm new password"
      %br/
      = password_field_tag :password_confirmation
      %br
      = submit_tag 'Reset'  

%div{:class => "panel panel-default"}
  %h2 Expired Licenses
  

%div{:class => "panel panel-default"}
  %h2 Approve Therapist

app/views/dashboards/patient_dashboard.html.haml
%h1 Patient Dashboard
%table{:border => "1", :width => "100%"}
  %tbody
    %tr
      %td
        %h3 My Therapist
        - if !@my_therapists.blank?
          - @my_therapists.each do |therapist|
            = therapist.display_name
            = link_to("Request Appointment", new_appointment_path(therapist_id: therapist.id))
            |
            = link_to("Message", new_conversation_path(recipient: therapist.user_id))
            |
            = link_to("View Profile", therapist_profile_path(therapist.therapist_id))
          %br
      %td
        %h3 My Appointments
        - if !@my_appointments.blank?
          = render @my_appointments 
      %td
        %h3 My Messages
        = render @conversations
        %h3 My Invitations
        - if !@my_invitations.blank?
          - @my_invitations.each do |invitation|
            = invitation.display_name
            = link_to("Accept Invitation", accept_invitation_from_patient_path(id: invitation.user_id))
          %br

app/views/dashboards/therapist_dashboard.html.haml
%h1 Therapist Dashboard
%table{:border => "1", :width => "100%"}
  %tbody
    %tr
      %td
        %h3 My Patients
        - if !@my_patients.blank? 
          - @my_patients.each do |patient|
            = patient.display_name
            = link_to("Request Appointment", new_appointment_path(patient_id: patient.id))
            |
            = link_to("Message", new_conversation_path(recipient: patient.user_id))
            |
            = link_to("Patient Profile", therapist_patient_path(patient_id: patient.patient_id))
            %br
                            
      %td
        %h3 My Appointments
        - if !@my_appointments.blank?
          = render @my_appointments 
      %td
        %h3 My Messages
        = render @conversations